occupancy_grid:
  side: 200
  density_threshold: 15 # Threshold for occupied voxels

segmentation:
  ground_lower: -1
  ground_upper: -0.0
  z_center: 0.1
  z_band_thickness: 1.5
  grid_resolution: 100   # lateral resolution for x and y, and also z
  grid_min: -1.0     # domain minimum for each axis
  grid_max: 1.0      # domain maximum for each axis
  voxel_size: 0.02 
